services:
  db:
    image: postgres:15-alpine
    container_name: db_proyecto_prod
    restart: always
    environment:
      POSTGRES_USER: user_prod
      POSTGRES_PASSWORD: password_prod
      POSTGRES_DB: mi_api_db_prod
    ports:
      - "5432:5432"
    volumes:
      - db-data-prod:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: cache_proyecto_prod
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: ASISYA_ev.Api/Dockerfile
    container_name: ASISYA_ev_prod
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=mi_api_db_prod;Username=user_prod;Password=password_prod;
      CacheSettings__RedisHost: cache:6379
      CacheSettings__ListTtlMinutes: 2
      CacheSettings__DetailTtlMinutes: 10
    ports:
      - "80:8080"
    depends_on:
      - db
      - cache

volumes:
  db-data-prod:
